# Generated by Django 5.1.7 on 2025-04-21 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('school', 'School'), ('internship', 'Internship'), ('financial_aid', 'Financial Aid'), ('scholarship', 'Scholarship'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('platform', models.ForeignKey(blank=True, choices=[('common_app', 'Common App'), ('questbridge', 'Questbridge'), ('cuny', 'CUNY'), ('suny', 'SUNY'), ('school_specific', 'School Specific')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_apps', to='tasks.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=255)),
                ('applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tasks.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
