# Generated by Django 5.2.3 on 2025-06-16 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('common_app', 'Common App'), ('questbridge', 'Questbridge'), ('cuny', 'CUNY'), ('suny', 'SUNY')], max_length=255)),
                ('category', models.CharField(choices=[('school', 'School'), ('internship', 'Internship'), ('financial_aid', 'Financial Aid'), ('scholarship', 'Scholarship'), ('other', 'Other')], default='school', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('school', 'School'), ('internship', 'Internship'), ('financial_aid', 'Financial Aid'), ('scholarship', 'Scholarship'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('platform_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.platformtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformTemplateToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tasks.platformtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tasks.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformTemplateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.platformtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_platforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'platform_template'), name='unique_user_platform_submission')],
            },
        ),
    ]
