# Generated by Django 5.1.7 on 2025-04-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='applications',
            new_name='application',
        ),
    ]
