# Generated by Django 5.1.7 on 2025-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_applications_todo_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.CharField(blank=True, choices=[('activities', 'Activity List'), ('application', 'Application'), ('fit', 'Assess College Fit'), ('interview', 'Interview'), ('lor', 'Letters of Recommendation'), ('story', 'Personal Story'), ('transcript', 'Transcript'), ('test_scores', 'Test Scores'), ('writing', 'Writing'), ('other', 'Other')], max_length=255),
        ),
    ]
