# Generated by Django 5.1.7 on 2025-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
