# Generated by Django 5.1.7 on 2025-04-28 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_todo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('common_app', 'Common App'), ('questbridge', 'Questbridge'), ('cuny', 'CUNY'), ('suny', 'SUNY')], max_length=255)),
                ('category', models.CharField(choices=[('school', 'School'), ('internship', 'Internship'), ('financial_aid', 'Financial Aid'), ('scholarship', 'Scholarship'), ('other', 'Other')], default='school', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='platform',
            field=models.ForeignKey(blank=True, choices=[('common_app', 'Common App'), ('questbridge', 'Questbridge'), ('cuny', 'CUNY'), ('suny', 'SUNY')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_apps', to='tasks.application'),
        ),
        migrations.CreateModel(
            name='PlatformTemplateToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tasks.platformtemplate')),
            ],
        ),
    ]
