# Generated by Django 5.1.7 on 2025-04-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_application_platform_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='platform',
        ),
    ]
