# Generated by Django 5.1.7 on 2025-04-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('grade', models.IntegerField(choices=[('11', '11th Grade'), ('12', '12th Grade')])),
                ('google_doc_url', models.URLField()),
            ],
        ),
    ]
