# Generated by Django 5.1.7 on 2025-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmaterial',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
