# Generated by Django 5.1.7 on 2025-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshopmaterial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopmaterial',
            name='google_doc_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
