# Generated by Django 5.1.7 on 2025-04-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshopmaterial_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopmaterial',
            name='visible',
        ),
    ]
