# Generated by Django 5.1.7 on 2025-04-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_remove_workshopmaterial_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopmaterial',
            name='google_doc_url',
        ),
        migrations.AddField(
            model_name='workshopmaterial',
            name='google_doc_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
