# Generated by Django 5.1.7 on 2025-05-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_remove_workshopmaterial_google_doc_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmaterial',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
