# Generated by Django 5.2.3 on 2025-08-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_workshopmaterial_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmaterial',
            name='google_sheets_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='workshopmaterial',
            name='google_slides_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
