# Generated by Django 5.2.3 on 2025-06-16 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee'), ('admin', 'Administrator')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee'), ('admin', 'Administrator')], max_length=255)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('college_attended', models.CharField(blank=True, max_length=255, null=True)),
                ('college_major', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('mentors', models.ManyToManyField(blank=True, related_name='mentees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
