# Generated by Django 5.1.7 on 2025-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_college_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
