# Generated by Django 5.1.7 on 2025-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_allowedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee'), ('admin', 'Administrator')], default='mentee', max_length=255),
            preserve_default=False,
        ),
    ]
