# Generated by Django 5.1.7 on 2025-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='category',
            field=models.CharField(choices=[('session', 'CAP Session'), ('general', 'General')], default='general', max_length=10),
        ),
    ]
