# Generated by Django 5.1.7 on 2025-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_calendarevent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='isAllDay',
            field=models.BooleanField(default=False),
        ),
    ]
