# Generated by Django 5.1.7 on 2025-05-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_calendarevent_isallday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('session', 'CAP Session')], default='general', max_length=10),
        ),
    ]
