# Generated by Django 5.2.3 on 2025-07-28 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_calendarevent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onesignal_notif_id', models.CharField(blank=True, max_length=80, null=True)),
                ('calendar_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_event', to='calendar_app.calendarevent')),
            ],
        ),
    ]
